name: Build and Deploy Flutter Web

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Remove old files in VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            rm -rf /var/www/html/*

      - name: Deploy using rsync (no extra build folder)
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: build/web/
          remote_path: /var/www/html/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
